package com.livescribe.web.registration.controller;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.livescribe.framework.exception.InvalidParameterException;
import com.livescribe.web.registration.util.PenId;

/**
 * Registration generated by hbm2java
 */
public class RegistrationData  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -5338016838708943494L;
	
	private PenId penId;
	
	private Long registrationId;
	private String displayId;
	private String appId;
	private Integer edition;
	private String penSerial; // This can either be pen serial number or display ID
	private String penName;
	private String firstName;
	private String lastName;
	private String email;
	private String locale;
	private String country;
	private Boolean optIn;

    public RegistrationData() {
    }

    public RegistrationData(String displayId, String appId, Integer edition, String penSerial, String penName, String firstName, String lastName, String email, String locale, String country, Boolean optIn) {
       this.displayId = displayId;
       this.appId = appId;
       this.edition = edition;
       this.penSerial = penSerial;
       this.penName = penName;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.locale = locale;
       this.country = country;
       this.optIn = optIn;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="registration_id", nullable=false)
    public Long getRegistrationId() {
        return this.registrationId;
    }
    
    public void setRegistrationId(Long registrationId) {
        this.registrationId = registrationId;
    }

    
    @Column(name="display_id", length=64)
    public String getDisplayId() {
        return this.displayId;
    }
    
    public void setDisplayId(String displayId) {
        this.displayId = displayId;
    }

    
    @Column(name="app_id", length=64)
    public String getAppId() {
        return this.appId;
    }
    
    public void setAppId(String appId) {
        this.appId = appId;
    }

    
    @Column(name="pen_serial", length=14)
    public String getPenSerial() {
        return this.penSerial;
    }
    
    public void setPenSerial(String penSerial) {
        this.penSerial = penSerial;
    }

    
    @Column(name="pen_name", length=64)
    public String getPenName() {
        return this.penName;
    }
    
    public void setPenName(String penName) {
        this.penName = penName;
    }

    
    @Column(name="first_name", length=64)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=64)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email", length=64)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="locale", length=45)
    public String getLocale() {
        return this.locale;
    }
    
    public void setLocale(String locale) {
        this.locale = locale;
    }

    
    @Column(name="country", length=64)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="opt_in")
    public Boolean getOptIn() {
        return this.optIn;
    }
    
    public void setOptIn(Boolean optIn) {
        this.optIn = optIn;
    }

	/**
	 * <p></p>
	 * 
	 * @return the edition
	 */
	public Integer getEdition() {
		return edition;
	}

	/**
	 * <p></p>
	 * 
	 * @param edition the edition to set
	 */
	public void setEdition(Integer edition) {
		this.edition = edition;
	}
	
	/**
	 * <p></p>
	 * 
	 * @return
	 * @throws InvalidParameterException 
	 */
	public PenId getPenId() throws InvalidParameterException {
		
		if (penId != null) {
			return this.penId;
		}
		
		if (penSerial == null || penSerial.isEmpty()) {
			throw new InvalidParameterException("Invalid penId parameter.");
		}

		this.penId = PenId.getPenIdObject(penSerial);
		return this.penId;
	}
}


