package com.livescribe.aws.heartbeat.orm;

// Generated Feb 14, 2012 4:14:46 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.livescribe.aws.heartbeat.annotation.MetricNodeAttribute;

/**
 * Diagnostic generated by hbm2java
 */
public class Diagnostic extends DataMetric {

	@MetricNodeAttribute(name = "sub_type", dataType = "java.lang.String")
	private String subType;
	
	@MetricNodeAttribute(name = "s3_location", dataType = "java.lang.String")
	private String s3Location;

	@MetricNodeAttribute(name = "test", dataType = "java.lang.Boolean")
	private Boolean isTestData;

	@MetricNodeAttribute(name = "time", dataType = "java.util.Date")
	private Date eventTime;

	public Diagnostic() {
	}

	public String getSubType() {
		return this.subType;
	}

	public void setSubType(String subType) {
		this.subType = subType;
	}

	public String getS3Location() {
		return this.s3Location;
	}

	public void setS3Location(String s3Location) {
		this.s3Location = s3Location;
	}

	public Boolean getIsTestData() {
		return this.isTestData;
	}

	public void setIsTestData(Boolean isTestData) {
		this.isTestData = isTestData;
	}

	public Date getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	@Override
	public String toString() {
		return "Diagnostic[" +
				" messageId=" + getMessageId() +
				" metricVersion=" + getMetricVersion() +
				" deviceId=" + getDeviceId() +
				" deviceType=" + getDeviceType() +
				" fwVersion=" + getFwVersion() +
				" subType=" + this.subType +
				" s3Location=" + this.s3Location +
				" isTestData=" + isTestData +
				" eventTime=" + eventTime.toString() +
				"]";
	}
}
