package com.livescribe.aws.heartbeat.orm;

// Generated Oct 18, 2011 2:32:03 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.livescribe.aws.heartbeat.annotation.MetricNodeAttribute;

/**
 * FirmwareUpdate generated by hbm2java
 */
public class FirmwareUpdate extends DataMetric {

	@MetricNodeAttribute(name="version", dataType="java.lang.String")
	private String updateVersion;
	
	@MetricNodeAttribute(name="revision", dataType="java.lang.String")
	private String svnRevision;
	
	@MetricNodeAttribute(name="buildTime", dataType="java.util.Date")
	private Date buildTime;
	
	@MetricNodeAttribute(name="test", dataType="java.lang.Boolean")
	private Boolean isTestData;
	
	@MetricNodeAttribute(name="time", dataType="java.util.Date")
	private Date eventTime;

	public FirmwareUpdate() {
	}

	public String getUpdateVersion() {
		return this.updateVersion;
	}

	public void setUpdateVersion(String updateVersion) {
		this.updateVersion = updateVersion;
	}

	public Boolean getIsTestData() {
		return this.isTestData;
	}

	public void setIsTestData(Boolean isTestData) {
		this.isTestData = isTestData;
	}

	public Date getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}
	
	public String getSvnRevision() {
		return svnRevision;
	}

	public void setSvnRevision(String svnRevision) {
		this.svnRevision = svnRevision;
	}

	public Date getBuildTime() {
		return buildTime;
	}

	public void setBuildTime(Date buildTime) {
		this.buildTime = buildTime;
	}

	@Override
	public String toString() {
		return "FirmwareUpdate[" +
				" messageId=" + getMessageId() +
				" metricVersion=" + getMetricVersion() +
				" deviceId=" + getDeviceId() +
				" deviceType=" + getDeviceType() +
				" fwVersion=" + getFwVersion() +
				" updateVersion=" + updateVersion +
				" svnRevision=" + svnRevision +
				" buildTime=" + buildTime.toString() +
				" isTestData=" + isTestData +
				" eventTime=" + eventTime.toString() +
				"]";
	}
}
