package com.livescribe.aws.heartbeat.orm;

// Generated Oct 18, 2011 2:32:03 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.livescribe.aws.heartbeat.annotation.MetricNodeAttribute;

/**
 * LaunchLine generated by hbm2java
 */
public class LaunchLine extends DataMetric {
	@MetricNodeAttribute(name="action", dataType="java.lang.String")
	private String action;
	
	@MetricNodeAttribute(name="class", dataType="java.lang.String")
	private String classAttr;
	
	@MetricNodeAttribute(name="test", dataType="java.lang.Boolean")
	private Boolean isTestData;
	
	@MetricNodeAttribute(name="time", dataType="java.util.Date")
	private Date eventTime;

	public LaunchLine() {
	}

	public Date getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	public Boolean getIsTestData() {
		return isTestData;
	}

	public void setIsTestData(Boolean isTestData) {
		this.isTestData = isTestData;
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getClassAttr() {
		return classAttr;
	}

	public void setClassAttr(String classAttr) {
		this.classAttr = classAttr;
	}

	@Override
	public String toString() {
		return "LaunchLine[" +
				" messageId=" + getMessageId() +
				" metricVersion=" + getMetricVersion() +
				" deviceId=" + getDeviceId() +
				" deviceType=" + getDeviceType() +
				" fwVersion=" + getFwVersion() +
				" action=" + action +
				" classAttr=" + classAttr +
				" isTestData=" + isTestData +
				" eventTime=" + eventTime.toString() +
				"]";
	}
}
