package com.livescribe.aws.heartbeat.orm;

//Generated Feb 14, 2012 4:16:39 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.livescribe.aws.heartbeat.msg.SQSMessage;

/**
 * MetricGroup generated by hbm2java
 */
public class MetricGroup implements java.io.Serializable {

	private Long metricGroupId;
	private String messageId;
	private Date metricSent;
	private Date created;
	private Set<Quickcmd> quickcmds = new HashSet<Quickcmd>(0);
	private Set<WifiOff> wifiOffs = new HashSet<WifiOff>(0);
	private Set<PaperReplay> paperReplaies = new HashSet<PaperReplay>(0);
	private Set<PenUndocked> penUndockeds = new HashSet<PenUndocked>(0);
	private Set<FirmwareUpdate> firmwareUpdates = new HashSet<FirmwareUpdate>(0);
	private Set<PageSwitch> pageSwitchs = new HashSet<PageSwitch>(0);
	private Set<PenOff> penOffs = new HashSet<PenOff>(0);
	private Set<DynnavplusCreated> dynnavplusCreateds = new HashSet<DynnavplusCreated>(0);
	private Set<Quickrecord> quickrecords = new HashSet<Quickrecord>(0);
	private Set<LaunchApp> launchApps = new HashSet<LaunchApp>(0);
	private Set<SwitchLang> switchLangs = new HashSet<SwitchLang>(0);
	private Set<LaunchLine> launchLines = new HashSet<LaunchLine>(0);
	private Set<Shortcut> shortcuts = new HashSet<Shortcut>(0);
	private Set<WifiOn> wifiOns = new HashSet<WifiOn>(0);
	private Set<UsbCommand> usbCommands = new HashSet<UsbCommand>(0);
	private Set<Crash> crashs = new HashSet<Crash>(0);


//	private Set penOns = new HashSet(0);
//	private Set captivePortals = new HashSet(0);
//	private Set buttonTaps = new HashSet(0);
//	private Set newHostSpots = new HashSet(0);
//	private Set diagnostics = new HashSet(0);
	
	public MetricGroup() {
	}

	public MetricGroup(SQSMessage message) {
		this.messageId = message.getMessageId();
		this.created = new Date();
		this.metricSent = message.getFirstAttemptSend();
	}

	public MetricGroup(Date metricSent) {
		this.metricSent = metricSent;
	}

	public MetricGroup(String messageId, Date metricSent, Date created,
			Set<Quickcmd> quickcmds, Set<WifiOff> wifiOffs, Set<PaperReplay> paperReplaies, Set<PenUndocked> penUndockeds,
			Set<FirmwareUpdate> firmwareUpdates, Set<PageSwitch> pageSwitchs, Set<PenOff> penOffs,
			Set<DynnavplusCreated> dynnavplusCreateds, Set<Quickrecord> quickrecords, Set<LaunchApp> launchApps,
			Set<SwitchLang> switchLangs, Set<LaunchLine> launchLines, Set<Shortcut> shortcuts, Set<WifiOn> wifiOns,
			Set<UsbCommand> usbCommands, Set<Crash> crashs) {
		this.messageId = messageId;
		this.metricSent = metricSent;
		this.created = created;
		this.quickcmds = quickcmds;
		this.wifiOffs = wifiOffs;
		this.paperReplaies = paperReplaies;
		this.penUndockeds = penUndockeds;
		this.firmwareUpdates = firmwareUpdates;
		this.pageSwitchs = pageSwitchs;
		this.penOffs = penOffs;
		this.dynnavplusCreateds = dynnavplusCreateds;
		this.quickrecords = quickrecords;
		this.launchApps = launchApps;
		this.switchLangs = switchLangs;
		this.launchLines = launchLines;
		this.shortcuts = shortcuts;
		this.wifiOns = wifiOns;
		this.usbCommands = usbCommands;
		this.crashs = crashs;
//		this.penOns = penOns;
//		this.captivePortals = captivePortals;
//		this.newHostSpots = newHostSpots;
//		this.diagnostics = diagnostics;
//		this.buttonTaps = buttonTaps;
	}

	public Long getMetricGroupId() {
		return this.metricGroupId;
	}

	public void setMetricGroupId(Long metricGroupId) {
		this.metricGroupId = metricGroupId;
	}

	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	public Date getMetricSent() {
		return this.metricSent;
	}

	public void setMetricSent(Date metricSent) {
		this.metricSent = metricSent;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Set<Quickcmd> getQuickcmds() {
		return this.quickcmds;
	}

	public void setQuickcmds(Set<Quickcmd> quickcmds) {
		this.quickcmds = quickcmds;
	}

	public Set<WifiOff> getWifiOffs() {
		return this.wifiOffs;
	}

	public void setWifiOffs(Set<WifiOff> wifiOffs) {
		this.wifiOffs = wifiOffs;
	}

	public Set<PaperReplay> getPaperReplaies() {
		return this.paperReplaies;
	}

	public void setPaperReplaies(Set<PaperReplay> paperReplaies) {
		this.paperReplaies = paperReplaies;
	}

	public Set<PenUndocked> getPenUndockeds() {
		return this.penUndockeds;
	}

	public void setPenUndockeds(Set<PenUndocked> penUndockeds) {
		this.penUndockeds = penUndockeds;
	}

	public Set<FirmwareUpdate> getFirmwareUpdates() {
		return this.firmwareUpdates;
	}

	public void setFirmwareUpdates(Set<FirmwareUpdate> firmwareUpdates) {
		this.firmwareUpdates = firmwareUpdates;
	}

	public Set<PageSwitch> getPageSwitchs() {
		return this.pageSwitchs;
	}

	public void setPageSwitchs(Set<PageSwitch> pageSwitchs) {
		this.pageSwitchs = pageSwitchs;
	}

	public Set<PenOff> getPenOffs() {
		return this.penOffs;
	}

	public void setPenOffs(Set<PenOff> penOffs) {
		this.penOffs = penOffs;
	}

	public Set<DynnavplusCreated> getDynnavplusCreateds() {
		return this.dynnavplusCreateds;
	}

	public void setDynnavplusCreateds(Set<DynnavplusCreated> dynnavplusCreateds) {
		this.dynnavplusCreateds = dynnavplusCreateds;
	}

	public Set<Quickrecord> getQuickrecords() {
		return this.quickrecords;
	}

	public void setQuickrecords(Set<Quickrecord> quickrecords) {
		this.quickrecords = quickrecords;
	}

	public Set<LaunchApp> getLaunchApps() {
		return this.launchApps;
	}

	public void setLaunchApps(Set<LaunchApp> launchApps) {
		this.launchApps = launchApps;
	}

	public Set<SwitchLang> getSwitchLangs() {
		return this.switchLangs;
	}

	public void setSwitchLangs(Set<SwitchLang> switchLangs) {
		this.switchLangs = switchLangs;
	}

	public Set<LaunchLine> getLaunchLines() {
		return this.launchLines;
	}

	public void setLaunchLines(Set<LaunchLine> launchLines) {
		this.launchLines = launchLines;
	}

	public Set<Shortcut> getShortcuts() {
		return this.shortcuts;
	}

	public void setShortcuts(Set<Shortcut> shortcuts) {
		this.shortcuts = shortcuts;
	}

	public Set<WifiOn> getWifiOns() {
		return this.wifiOns;
	}

	public void setWifiOns(Set<WifiOn> wifiOns) {
		this.wifiOns = wifiOns;
	}

	public Set<UsbCommand> getUsbCommands() {
		return this.usbCommands;
	}

	public void setUsbCommands(Set<UsbCommand> usbCommands) {
		this.usbCommands = usbCommands;
	}

	public Set<Crash> getCrashs() {
		return this.crashs;
	}

	public void setCrashs(Set<Crash> crashs) {
		this.crashs = crashs;
	}

	/*
	public Set getCaptivePortals() {
		return this.captivePortals;
	}

	public void setCaptivePortals(Set captivePortals) {
		this.captivePortals = captivePortals;
	}

	public Set getNewHostSpots() {
		return this.newHostSpots;
	}

	public void setNewHostSpots(Set newHostSpots) {
		this.newHostSpots = newHostSpots;
	}
	public Set getDiagnostics() {
		return this.diagnostics;
	}

	public void setDiagnostics(Set diagnostics) {
		this.diagnostics = diagnostics;
	}

	public Set getButtonTaps() {
		return this.buttonTaps;
	}

	public void setButtonTaps(Set buttonTaps) {
		this.buttonTaps = buttonTaps;
	}

	public Set getPenOns() {
		return this.penOns;
	}

	public void setPenOns(Set penOns) {
		this.penOns = penOns;
	}
	*/
}
