package com.livescribe.aws.heartbeat.orm;

// Generated Feb 14, 2012 4:14:46 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.livescribe.aws.heartbeat.annotation.MetricNodeAttribute;

/**
 * NewHostSpot generated by hbm2java
 */
public class NewHostSpot extends DataMetric {

	@MetricNodeAttribute(name = "url", dataType = "java.lang.String")
	private String url;
	
	@MetricNodeAttribute(name = "s3_location", dataType = "java.lang.String")
	private String s3Location;
	
	@MetricNodeAttribute(name = "test", dataType = "java.lang.Boolean")
	private Boolean isTestData;

	@MetricNodeAttribute(name = "time", dataType = "java.util.Date")
	private Date eventTime;

	public NewHostSpot() {
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getS3Location() {
		return this.s3Location;
	}

	public void setS3Location(String s3Location) {
		this.s3Location = s3Location;
	}

	public Boolean getIsTestData() {
		return this.isTestData;
	}

	public void setIsTestData(Boolean isTestData) {
		this.isTestData = isTestData;
	}

	public Date getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	@Override
	public String toString() {
		return "NewHostSpot[" +
				" messageId=" + getMessageId() +
				" metricVersion=" + getMetricVersion() +
				" deviceId=" + getDeviceId() +
				" deviceType=" + getDeviceType() +
				" fwVersion=" + getFwVersion() +
				" url=" + this.url +
				" s3Location=" + this.s3Location +
				" isTestData=" + isTestData +
				" eventTime=" + eventTime.toString() +
				"]";
	}
}
