package com.livescribe.aws.heartbeat.orm;

// Generated Oct 18, 2011 2:32:03 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.livescribe.aws.heartbeat.annotation.MetricNodeAttribute;

/**
 * PenOn generated by hbm2java
 */
public class PenOn extends DataMetric {

	@MetricNodeAttribute(name="device_action", dataType="java.lang.String")
	private String deviceAction;
	
	@MetricNodeAttribute(name="test", dataType="java.lang.Boolean")
	private Boolean isTestData;
	
	@MetricNodeAttribute(name="time", dataType="java.util.Date")
	private Date eventTime;

	public PenOn() {
	}

	public String getDeviceAction() {
		return this.deviceAction;
	}

	public void setDeviceAction(String deviceAction) {
		this.deviceAction = deviceAction;
	}

	public Boolean getIsTestData() {
		return this.isTestData;
	}

	public void setIsTestData(Boolean isTestData) {
		this.isTestData = isTestData;
	}

	public Date getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	@Override
	public String toString() {
		return "PenOn[" +
				" messageId=" + getMessageId() +
				" metricVersion=" + getMetricVersion() +
				" deviceId=" + getDeviceId() +
				" deviceType=" + getDeviceType() +
				" fwVersion=" + getFwVersion() +
				" deviceAction=" + this.deviceAction +
				" isTestData=" + isTestData +
				" eventTime=" + eventTime.toString() +
				"]";
	}
}
