package com.livescribe.aws.heartbeat.orm;

// Generated Nov 9, 2011 4:41:39 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.livescribe.aws.heartbeat.annotation.MetricNodeAttribute;

/**
 * Shortcut generated by hbm2java
 */
public class Shortcut extends DataMetric {

	@MetricNodeAttribute(name="action", dataType="java.lang.String")
	private String action;
	
	@MetricNodeAttribute(name="shortcutId", dataType="java.lang.Integer")
	private Integer shortcutId;
	
	@MetricNodeAttribute(name="cmd", dataType="java.lang.String")
	private String cmd;
	
	@MetricNodeAttribute(name="test", dataType="java.lang.Boolean")
	private Boolean isTestData;
	
	@MetricNodeAttribute(name="time", dataType="java.util.Date")
	private Date eventTime;

	public Shortcut() {
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public Integer getShortcutId() {
		return shortcutId;
	}

	public void setShortcutId(Integer shortcutId) {
		this.shortcutId = shortcutId;
	}

	public String getCmd() {
		return cmd;
	}

	public void setCmd(String cmd) {
		this.cmd = cmd;
	}

	public Boolean getIsTestData() {
		return isTestData;
	}

	public void setIsTestData(Boolean isTestData) {
		this.isTestData = isTestData;
	}

	public Date getEventTime() {
		return eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	@Override
	public String toString() {
		return "Shortcut[" +
				" messageId=" + getMessageId() +
				" metricVersion=" + getMetricVersion() +
				" deviceId=" + getDeviceId() +
				" deviceType=" + getDeviceType() +
				" fwVersion=" + getFwVersion() +
				" action=" + action +
				" shortcutId=" + shortcutId +
				" cmd=" + cmd +
				" isTestData=" + isTestData +
				" eventTime=" + eventTime.toString() +
				"]";
	}
}
