package com.livescribe.aws.heartbeat.orm;

// Generated Nov 9, 2011 4:41:39 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.livescribe.aws.heartbeat.annotation.MetricNodeAttribute;

/**
 * WifiOff generated by hbm2java
 */
public class WifiOff extends DataMetric {

	@MetricNodeAttribute(name = "test", dataType = "java.lang.Boolean")
	private Boolean isTestData;

	@MetricNodeAttribute(name = "time", dataType = "java.util.Date")
	private Date eventTime;

	public WifiOff() {
	}

	public Boolean getIsTestData() {
		return isTestData;
	}

	public void setIsTestData(Boolean isTestData) {
		this.isTestData = isTestData;
	}

	public Date getEventTime() {
		return eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	@Override
	public String toString() {
		return "WifiOff[" +
				" messageId=" + getMessageId() +
				" metricVersion=" + getMetricVersion() +
				" deviceId=" + getDeviceId() +
				" deviceType=" + getDeviceType() +
				" fwVersion=" + getFwVersion() +
				" isTestData=" + isTestData +
				" eventTime=" + eventTime.toString() +
				"]";
	}
}
