insert into us_state (is_active, state_name, state_abbrev) values (1, 'ALABAMA', 'AL');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'ALASKA', 'AK');
insert into us_state (is_active, state_name, state_abbrev) values (0, 'AMERICAN SAMOA', 'AS');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'ARIZONA', 'AZ');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'ARKANSAS', 'AR');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'CALIFORNIA', 'CA');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'COLORADO', 'CO');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'CONNECTICUT', 'CT');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'DELAWARE', 'DE');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'DISTRICT OF COLUMBIA', 'DC');
insert into us_state (is_active, state_name, state_abbrev) values (0, 'FEDERATED STATES OF MICRONESIA', 'FM');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'FLORIDA', 'FL');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'GEORGIA', 'GA');
insert into us_state (is_active, state_name, state_abbrev) values (0, 'GUAM', 'GU');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'HAWAII', 'HI');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'IDAHO', 'ID');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'ILLINOIS', 'IL');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'INDIANA', 'IN');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'IOWA', 'IA');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'KANSAS', 'KS');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'KENTUCKY', 'KY');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'LOUISIANA', 'LA');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'MAINE', 'ME');
insert into us_state (is_active, state_name, state_abbrev) values (0, 'MARSHALL ISLANDS', 'MH');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'MARYLAND', 'MD');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'MASSACHUSETTS', 'MA');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'MICHIGAN', 'MI');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'MINNESOTA', 'MN');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'MISSISSIPPI', 'MS');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'MISSOURI', 'MO');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'MONTANA', 'MT');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'NEBRASKA', 'NE');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'NEVADA', 'NV');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'NEW HAMPSHIRE', 'NH');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'NEW JERSEY', 'NJ');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'NEW MEXICO', 'NM');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'NEW YORK', 'NY');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'NORTH CAROLINA', 'NC');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'NORTH DAKOTA', 'ND');
insert into us_state (is_active, state_name, state_abbrev) values (0, 'NORTHERN MARIANA ISLANDS', 'MP');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'OHIO', 'OH');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'OKLAHOMA', 'OK');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'OREGON', 'OR');
insert into us_state (is_active, state_name, state_abbrev) values (0, 'PALAU', 'PW');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'PENNSYLVANIA', 'PA');
insert into us_state (is_active, state_name, state_abbrev) values (0, 'PUERTO RICO', 'PR');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'RHODE ISLAND', 'RI');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'SOUTH CAROLINA', 'SC');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'SOUTH DAKOTA', 'SD');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'TENNESSEE', 'TN');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'TEXAS', 'TX');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'UTAH', 'UT');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'VERMONT', 'VT');
insert into us_state (is_active, state_name, state_abbrev) values (0, 'VIRGIN ISLANDS', 'VI');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'VIRGINIA', 'VA');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'WASHINGTON', 'WA');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'WEST VIRGINIA', 'WV');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'WISCONSIN', 'WI');
insert into us_state (is_active, state_name, state_abbrev) values (1, 'WYOMING', 'WY');
