package com.livescribe.community.orm;
// Generated Jul 12, 2010 8:44:50 PM by Hibernate Tools 3.3.0.GA


import java.util.Date;

/**
 * ActiveUser generated by hbm2java
 */
public class ActiveUser  implements java.io.Serializable {


     private byte[] primaryKey;
     private String domain;
     private Date loginTime;
     private String loginToken;
     private byte[] userId;

    public ActiveUser() {
    }

	
    public ActiveUser(byte[] primaryKey) {
        this.primaryKey = primaryKey;
    }
    public ActiveUser(byte[] primaryKey, String domain, Date loginTime, String loginToken, byte[] userId) {
       this.primaryKey = primaryKey;
       this.domain = domain;
       this.loginTime = loginTime;
       this.loginToken = loginToken;
       this.userId = userId;
    }
   
    public byte[] getPrimaryKey() {
        return this.primaryKey;
    }
    
    public void setPrimaryKey(byte[] primaryKey) {
        this.primaryKey = primaryKey;
    }
    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }
    public Date getLoginTime() {
        return this.loginTime;
    }
    
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
    public String getLoginToken() {
        return this.loginToken;
    }
    
    public void setLoginToken(String loginToken) {
        this.loginToken = loginToken;
    }
    public byte[] getUserId() {
        return this.userId;
    }
    
    public void setUserId(byte[] userId) {
        this.userId = userId;
    }




}


