package com.livescribe.community.orm;
// Generated Jun 17, 2010 10:50:10 AM by Hibernate Tools 3.3.0.GA


import java.sql.Clob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * UGCategory generated by hbm2java
 */
public class UGCategory  implements java.io.Serializable {


     private byte[] primaryKey;
     private String displayName;
     private Clob metaInfo;

    public UGCategory() {
    }

	
    public UGCategory(byte[] primaryKey) {
        this.primaryKey = primaryKey;
    }
    public UGCategory(byte[] primaryKey, String displayName, Clob metaInfo) {
       this.primaryKey = primaryKey;
       this.displayName = displayName;
       this.metaInfo = metaInfo;
    }
   
    public byte[] getPrimaryKey() {
        return this.primaryKey;
    }
    
    public void setPrimaryKey(byte[] primaryKey) {
        this.primaryKey = primaryKey;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public Clob getMetaInfo() {
        return this.metaInfo;
    }
    
    public void setMetaInfo(Clob metaInfo) {
        this.metaInfo = metaInfo;
    }

    public static void main(String args[]) {
    	
    	Connection conn = null;
    	Statement stmt = null;
    	try {
	    	Class.forName("com.frontbase.jdbc.FBJDriver");
	    	conn = DriverManager.getConnection("jdbc:frontbase://db1-test.pensoft.local/qa.consumer/user=_system/isolation=read_committed/locking=deferred/readonly=false/");
	    	stmt = conn.createStatement();
	    	ResultSet rset = stmt.executeQuery("select * from UGCategory where primaryKey = x'00000A0101C90000F1D502000000011760AD35E3203CE0DE'");
	    	ResultSetMetaData rsmd = rset.getMetaData();
	    	for (int i = 1; i <= rsmd.getColumnCount(); i++) {
	    		int colType = rsmd.getColumnType(i);
	    		String colTypeName = rsmd.getColumnTypeName(i);
	    		String dispName = rsmd.getColumnName(i);
	    		System.out.println(dispName + " " + colTypeName + " " + colType);
	    	}
//	    	ResultSet rset = stmt.executeQuery("select * from UGCategory where displayName = 'Random'");
//    	"00000A0101C90000F1D502000000011760AD35E3203CE0DE"
//    	"Random"
	    	stmt.close();
	    	conn.close();
    	}
    	catch (ClassNotFoundException cnfe) {
    		cnfe.printStackTrace();
    	}
    	catch (SQLException sqle) {
    		sqle.printStackTrace();
    	}
    	finally {
    	}
    }
}


