package com.livescribe.community.orm;
// Generated Jul 1, 2010 11:08:08 AM by Hibernate Tools 3.3.0.GA


import java.sql.Clob;
import java.util.Date;

/**
 * UGComment generated by hbm2java
 */
public class UGComment  implements java.io.Serializable {


     private byte[] primaryKey;
     private Clob contentDescription;
     private byte[] commenterKey;
     private String displayName;
     private Clob metaInfo;
     private double rating;
     private byte[] ugFileKey;
     private Date postedDate;
     private String ipAddress;
     private String isSafeComment;
     private int inappropriateCounter;

    public UGComment() {
    }

	
    public UGComment(byte[] primaryKey) {
        this.primaryKey = primaryKey;
    }
    public UGComment(byte[] primaryKey, Clob contentDescription, byte[] commenterKey, String displayName, Clob metaInfo, double rating, byte[] ugFileKey, Date postedDate, String ipAddress, String isSafeComment, int inappropriateCounter) {
       this.primaryKey = primaryKey;
       this.contentDescription = contentDescription;
       this.commenterKey = commenterKey;
       this.displayName = displayName;
       this.metaInfo = metaInfo;
       this.rating = rating;
       this.ugFileKey = ugFileKey;
       this.postedDate = postedDate;
       this.ipAddress = ipAddress;
       this.isSafeComment = isSafeComment;
       this.inappropriateCounter = inappropriateCounter;
    }
   
    public byte[] getPrimaryKey() {
        return this.primaryKey;
    }
    
    public void setPrimaryKey(byte[] primaryKey) {
        this.primaryKey = primaryKey;
    }
    public Clob getContentDescription() {
        return this.contentDescription;
    }
    
    public void setContentDescription(Clob contentDescription) {
        this.contentDescription = contentDescription;
    }
    public byte[] getCommenterKey() {
        return this.commenterKey;
    }
    
    public void setCommenterKey(byte[] commenterKey) {
        this.commenterKey = commenterKey;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public Clob getMetaInfo() {
        return this.metaInfo;
    }
    
    public void setMetaInfo(Clob metaInfo) {
        this.metaInfo = metaInfo;
    }
    public double getRating() {
        return this.rating;
    }
    
    public void setRating(double rating) {
        this.rating = rating;
    }
    public byte[] getUgFileKey() {
        return this.ugFileKey;
    }
    
    public void setUgFileKey(byte[] ugFileKey) {
        this.ugFileKey = ugFileKey;
    }
    public Date getPostedDate() {
        return this.postedDate;
    }
    
    public void setPostedDate(Date postedDate) {
        this.postedDate = postedDate;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    public String getIsSafeComment() {
        return this.isSafeComment;
    }
    
    public void setIsSafeComment(String isSafeComment) {
        this.isSafeComment = isSafeComment;
    }
    public int getInappropriateCounter() {
        return this.inappropriateCounter;
    }
    
    public void setInappropriateCounter(int inappropriateCounter) {
        this.inappropriateCounter = inappropriateCounter;
    }




}


