package com.livescribe.community.orm;
// Generated Jun 17, 2010 10:50:10 AM by Hibernate Tools 3.3.0.GA


import java.sql.Blob;
import java.sql.Clob;
import java.util.Date;

/**
 * UserProfile generated by hbm2java
 */
public class UserProfile  implements java.io.Serializable {


     private String shortId;
     private byte[] addressKey;
     private Integer birthYear;
     private String email;
     private String firstName;
     private Integer gradYear;
     private Integer isMLSActive;
     private String lastName;
     private String major;
     private Clob metaInfo;
     private String occupation;
     private byte[] primaryKey;
     private Blob profilePicture;
     private String profilePictureMimeType;
     private String profilePictureName;
     private String screenName;
     private String sendEmail;
     private String sex;
     private String university;
     private Date lastModifyDate;
     private byte[] developerProfileKey;
     private String organization;
     private String phone;
     private String userPassword;
     private String passwordResetString;
     private String fk_avetti_customerID;
     private String fk_avetti_password;
     private Date createdate;
     private byte[] fk_preferred_country;

    public UserProfile() {
    }

	
    public UserProfile(String shortId) {
        this.shortId = shortId;
    }
    public UserProfile(String shortId, byte[] addressKey, Integer birthYear, String email, String firstName, Integer gradYear, Integer isMLSActive, String lastName, String major, Clob metaInfo, String occupation, byte[] primaryKey, Blob profilePicture, String profilePictureMimeType, String profilePictureName, String screenName, String sendEmail, String sex, String university, Date lastModifyDate, byte[] developerProfileKey, String organization, String phone, String userPassword, String passwordResetString, String fk_avetti_customerID, String fk_avetti_password, Date createdate, byte[] fk_preferred_country) {
       this.shortId = shortId;
       this.addressKey = addressKey;
       this.birthYear = birthYear;
       this.email = email;
       this.firstName = firstName;
       this.gradYear = gradYear;
       this.isMLSActive = isMLSActive;
       this.lastName = lastName;
       this.major = major;
       this.metaInfo = metaInfo;
       this.occupation = occupation;
       this.primaryKey = primaryKey;
       this.profilePicture = profilePicture;
       this.profilePictureMimeType = profilePictureMimeType;
       this.profilePictureName = profilePictureName;
       this.screenName = screenName;
       this.sendEmail = sendEmail;
       this.sex = sex;
       this.university = university;
       this.lastModifyDate = lastModifyDate;
       this.developerProfileKey = developerProfileKey;
       this.organization = organization;
       this.phone = phone;
       this.userPassword = userPassword;
       this.passwordResetString = passwordResetString;
       this.fk_avetti_customerID = fk_avetti_customerID;
       this.fk_avetti_password = fk_avetti_password;
       this.createdate = createdate;
       this.fk_preferred_country = fk_preferred_country;
    }
   
    public String getShortId() {
        return this.shortId;
    }
    
    public void setShortId(String shortId) {
        this.shortId = shortId;
    }
    public byte[] getAddressKey() {
        return this.addressKey;
    }
    
    public void setAddressKey(byte[] addressKey) {
        this.addressKey = addressKey;
    }
    public Integer getBirthYear() {
        return this.birthYear;
    }
    
    public void setBirthYear(Integer birthYear) {
        this.birthYear = birthYear;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public Integer getGradYear() {
        return this.gradYear;
    }
    
    public void setGradYear(Integer gradYear) {
        this.gradYear = gradYear;
    }
    public Integer getIsMLSActive() {
        return this.isMLSActive;
    }
    
    public void setIsMLSActive(Integer isMLSActive) {
        this.isMLSActive = isMLSActive;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }
    public Clob getMetaInfo() {
        return this.metaInfo;
    }
    
    public void setMetaInfo(Clob metaInfo) {
        this.metaInfo = metaInfo;
    }
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }
    public byte[] getPrimaryKey() {
        return this.primaryKey;
    }
    
    public void setPrimaryKey(byte[] primaryKey) {
        this.primaryKey = primaryKey;
    }
    public Blob getProfilePicture() {
        return this.profilePicture;
    }
    
    public void setProfilePicture(Blob profilePicture) {
        this.profilePicture = profilePicture;
    }
    public String getProfilePictureMimeType() {
        return this.profilePictureMimeType;
    }
    
    public void setProfilePictureMimeType(String profilePictureMimeType) {
        this.profilePictureMimeType = profilePictureMimeType;
    }
    public String getProfilePictureName() {
        return this.profilePictureName;
    }
    
    public void setProfilePictureName(String profilePictureName) {
        this.profilePictureName = profilePictureName;
    }
    public String getScreenName() {
        return this.screenName;
    }
    
    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }
    public String getSendEmail() {
        return this.sendEmail;
    }
    
    public void setSendEmail(String sendEmail) {
        this.sendEmail = sendEmail;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getUniversity() {
        return this.university;
    }
    
    public void setUniversity(String university) {
        this.university = university;
    }
    public Date getLastModifyDate() {
        return this.lastModifyDate;
    }
    
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }
    public byte[] getDeveloperProfileKey() {
        return this.developerProfileKey;
    }
    
    public void setDeveloperProfileKey(byte[] developerProfileKey) {
        this.developerProfileKey = developerProfileKey;
    }
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getPasswordResetString() {
        return this.passwordResetString;
    }
    
    public void setPasswordResetString(String passwordResetString) {
        this.passwordResetString = passwordResetString;
    }
    public String getFk_avetti_customerID() {
        return this.fk_avetti_customerID;
    }
    
    public void setFk_avetti_customerID(String fk_avetti_customerID) {
        this.fk_avetti_customerID = fk_avetti_customerID;
    }
    public String getFk_avetti_password() {
        return this.fk_avetti_password;
    }
    
    public void setFk_avetti_password(String fk_avetti_password) {
        this.fk_avetti_password = fk_avetti_password;
    }
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
    public byte[] getFk_preferred_country() {
        return this.fk_preferred_country;
    }
    
    public void setFk_preferred_country(byte[] fk_preferred_country) {
        this.fk_preferred_country = fk_preferred_country;
    }




}


